# Generated by Django 3.2.16 on 2023-01-06 22:54

from django.conf import settings
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Обязательно для заполнения. Максимум 255 символов.', max_length=150, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательно для заполнения.Максимум 150 букв.', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Обязательно для заполнения.Максимум 150 букв.', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='Обязательно для заполнения.Максимум 150 букв.', max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='subscribe',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения. От 3 до 150 букв.', max_length=150, unique=True, validators=[users.validators.MinLenValidator(min_len=3), users.validators.OneOfTwoValidator()], verbose_name='Уникальный юзернейм'),
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(check=models.Q(('username__length__gte', 3)), name='\nusername too short\n'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
